# -*- coding: utf-8 -*-
from PyQt5.QtWidgets import (
    QWidget, QVBoxLayout, QHBoxLayout,
    QLabel, QComboBox, QLineEdit, QPushButton, QCheckBox,
    QTableWidget, QHeaderView, QGroupBox, QSpinBox,
    QTabWidget, QListWidget, QAbstractItemView, QPlainTextEdit,
)
from PyQt5.QtCore import Qt
import pyqtgraph as pg


def setup_ui(main_window):
    mw = main_window
    mw.setWindowTitle('CAN 总线调试上位机 V2.0')
    mw.resize(1280, 800)
    pg.setConfigOptions(antialias=True, background='k', foreground='w')
    central = QWidget()
    mw.setCentralWidget(central)
    root = QVBoxLayout(central)
    root.setContentsMargins(6, 6, 6, 6)
    root.setSpacing(4)
    _build_top_bar(mw, root)
    mw.main_tab = QTabWidget()
    root.addWidget(mw.main_tab)
    _build_tab_monitor(mw)
    _build_tab_waveform(mw)
    _build_tab_send(mw)
    _build_tab_capture(mw)
    _build_tab_parse(mw)


def _build_top_bar(mw, root):
    grp = QGroupBox('连接配置')
    grp.setMaximumHeight(90)
    tb = QHBoxLayout(grp)
    tb.setSpacing(8)
    tb.addWidget(QLabel('接口:'))
    mw.interface_combo = QComboBox()
    mw.interface_combo.addItems([
        'pcan',         # PEAK PCAN-USB/PCIe
        'slcan',        # Serial CAN (LAWICEL / CANable)
        'socketcan',    # Linux SocketCAN
        'virtual',      # Software virtual bus (no hardware)
        'kvaser',       # Kvaser USB/PCIe
        'ixxat',        # HMS IXXAT USB/PCIe
        'vector',       # Vector VN-series (needs XL-Driver)
        'gs_usb',       # candleLight / USB2CAN (Linux)
        'canalystii',   # 创芯科技 CANalyst-II
        'nican',        # National Instruments NI-CAN
        'systec',       # SYS TEC USB-CANmodul
        'neovi',        # Intrepid neoVI
        'usb2can',      # 8devices USB2CAN
        'cantact',      # CANtact USB
        'robotell',     # Robotell USB-CAN
        'seeedstudio',  # Seeed Studio CAN HAT
        'udp_multicast',# UDP multicast virtual bus
    ])
    mw.interface_combo.setFixedWidth(120)
    tb.addWidget(mw.interface_combo)
    tb.addWidget(QLabel('通道:'))
    mw.channel_combo = QComboBox()
    mw.channel_combo.setEditable(True)
    mw.channel_combo.addItems(['PCAN_USBBUS1', 'PCAN_USBBUS2', '/dev/ttyUSB0', 'vcan0'])
    mw.channel_combo.setFixedWidth(140)
    tb.addWidget(mw.channel_combo)
    tb.addWidget(QLabel('波特率:'))
    mw.bitrate_combo = QComboBox()
    mw.bitrate_combo.addItems(['125000', '250000', '500000', '1000000'])
    mw.bitrate_combo.setCurrentText('500000')
    mw.bitrate_combo.setFixedWidth(90)
    tb.addWidget(mw.bitrate_combo)
    mw.fd_check = QCheckBox('CAN-FD')
    tb.addWidget(mw.fd_check)
    tb.addWidget(QLabel('FD 预设:'))
    mw.fd_preset_combo = QComboBox()
    mw.fd_preset_combo.addItems(['500k/2M', '500k/1M', '250k/2M', '250k/500k', '1M/4M'])
    mw.fd_preset_combo.setFixedWidth(95)
    mw.fd_preset_combo.setEnabled(False)
    tb.addWidget(mw.fd_preset_combo)
    tb.addSpacing(16)
    mw.dbc_btn = QPushButton('加载 DBC')
    mw.dbc_btn.setFixedWidth(90)
    tb.addWidget(mw.dbc_btn)
    mw.dbc_label = QLabel('DBC: 未加载')
    mw.dbc_label.setMinimumWidth(160)
    tb.addWidget(mw.dbc_label)
    tb.addSpacing(16)
    mw.connect_btn = QPushButton('打开 CAN')
    mw.connect_btn.setFixedWidth(90)
    mw.connect_btn.setStyleSheet('QPushButton { background: #2a6; color: white; font-weight: bold; }')
    tb.addWidget(mw.connect_btn)
    mw.status_label = QLabel('状态: 未连接')
    mw.status_label.setMinimumWidth(160)
    tb.addWidget(mw.status_label)
    tb.addStretch()
    root.addWidget(grp)


def _build_tab_monitor(mw):
    tab = QWidget()
    layout = QVBoxLayout(tab)
    layout.setContentsMargins(4, 4, 4, 4)
    ctrl = QHBoxLayout()
    ctrl.addWidget(QLabel('过滤 ID (hex):'))
    mw.filter_id_edit = QLineEdit()
    mw.filter_id_edit.setPlaceholderText('留空=全显示')
    mw.filter_id_edit.setFixedWidth(120)
    ctrl.addWidget(mw.filter_id_edit)
    mw.monitor_clear_btn = QPushButton('清空')
    mw.monitor_clear_btn.setFixedWidth(60)
    ctrl.addWidget(mw.monitor_clear_btn)
    mw.autoscroll_check = QCheckBox('自动滚动')
    mw.autoscroll_check.setChecked(True)
    ctrl.addWidget(mw.autoscroll_check)
    mw.raw_monitor_check = QCheckBox('启用监控')
    mw.raw_monitor_check.setChecked(True)
    ctrl.addWidget(mw.raw_monitor_check)
    ctrl.addStretch()
    layout.addLayout(ctrl)
    mw.monitor_table = QTableWidget(0, 5)
    mw.monitor_table.setHorizontalHeaderLabels(['时间(s)', 'ID', 'DLC', '数据(Hex)', 'DBC 解析'])
    mw.monitor_table.horizontalHeader().setSectionResizeMode(3, QHeaderView.Stretch)
    mw.monitor_table.horizontalHeader().setSectionResizeMode(4, QHeaderView.Stretch)
    mw.monitor_table.setColumnWidth(0, 90)
    mw.monitor_table.setColumnWidth(1, 80)
    mw.monitor_table.setColumnWidth(2, 45)
    mw.monitor_table.setEditTriggers(QAbstractItemView.NoEditTriggers)
    mw.monitor_table.setSelectionBehavior(QAbstractItemView.SelectRows)
    mw.monitor_table.verticalHeader().setVisible(False)
    mw.monitor_table.setAlternatingRowColors(True)
    layout.addWidget(mw.monitor_table)
    mw.main_tab.addTab(tab, '总线监控')


def _build_tab_waveform(mw):
    tab = QWidget()
    layout = QHBoxLayout(tab)
    layout.setContentsMargins(4, 4, 4, 4)
    layout.setSpacing(6)
    left = QWidget()
    left.setFixedWidth(220)
    ll = QVBoxLayout(left)
    ll.setContentsMargins(0, 0, 0, 0)
    ll.addWidget(QLabel('信号列表 (勾选绘制):'))
    mw.wave_search_edit = QLineEdit()
    mw.wave_search_edit.setPlaceholderText('搜索 ID / 信号名...')
    mw.wave_search_edit.setClearButtonEnabled(True)
    ll.addWidget(mw.wave_search_edit)
    mw.signal_list = QListWidget()
    mw.signal_list.setSelectionMode(QAbstractItemView.NoSelection)
    ll.addWidget(mw.signal_list)
    wc = QHBoxLayout()
    mw.wave_auto_y_check = QCheckBox('Y 自适应')
    mw.wave_auto_y_check.setChecked(True)
    wc.addWidget(mw.wave_auto_y_check)
    mw.wave_clear_btn = QPushButton('清空')
    mw.wave_clear_btn.setFixedWidth(50)
    wc.addWidget(mw.wave_clear_btn)
    ll.addLayout(wc)
    layout.addWidget(left)
    mw.wave_plot = pg.PlotWidget()
    mw.wave_plot.setLabel('bottom', '时间', units='s')
    mw.wave_plot.showGrid(x=True, y=True, alpha=0.3)
    mw.wave_plot.addLegend()
    layout.addWidget(mw.wave_plot)
    mw.main_tab.addTab(tab, '波形分析')


def _build_tab_send(mw):
    tab = QWidget()
    layout = QHBoxLayout(tab)
    layout.setContentsMargins(4, 4, 4, 4)
    layout.setSpacing(8)

    # ── DBC 构造报文 ──────────────────────────────────────────────
    dbc_grp = QGroupBox('基于 DBC 构造报文')
    dbc_grp.setMinimumWidth(520)
    dl = QVBoxLayout(dbc_grp)
    dl.setSpacing(4)

    # Top control bar
    ctrl = QHBoxLayout()
    mw.dbc_select_all_btn = QPushButton('全选')
    mw.dbc_select_all_btn.setFixedWidth(55)
    ctrl.addWidget(mw.dbc_select_all_btn)
    mw.dbc_deselect_all_btn = QPushButton('取消全选')
    mw.dbc_deselect_all_btn.setFixedWidth(70)
    ctrl.addWidget(mw.dbc_deselect_all_btn)
    ctrl.addSpacing(12)
    mw.dbc_send_once_btn = QPushButton('单次发送')
    mw.dbc_send_once_btn.setFixedWidth(80)
    ctrl.addWidget(mw.dbc_send_once_btn)
    ctrl.addWidget(QLabel('周期(ms):'))
    mw.dbc_period_spin = QSpinBox()
    mw.dbc_period_spin.setRange(1, 60000)
    mw.dbc_period_spin.setValue(100)
    mw.dbc_period_spin.setFixedWidth(65)
    ctrl.addWidget(mw.dbc_period_spin)
    mw.dbc_period_start_btn = QPushButton('启动')
    mw.dbc_period_start_btn.setFixedWidth(50)
    ctrl.addWidget(mw.dbc_period_start_btn)
    mw.dbc_period_stop_btn = QPushButton('停止')
    mw.dbc_period_stop_btn.setFixedWidth(50)
    mw.dbc_period_stop_btn.setEnabled(False)
    ctrl.addWidget(mw.dbc_period_stop_btn)
    mw.dbc_fd_check = QCheckBox('CAN-FD')
    ctrl.addWidget(mw.dbc_fd_check)
    ctrl.addStretch()
    dl.addLayout(ctrl)

    # Horizontal split: left message list | right signal table
    split = QHBoxLayout()
    split.setSpacing(6)

    left = QWidget()
    left.setFixedWidth(200)
    ll = QVBoxLayout(left)
    ll.setContentsMargins(0, 0, 0, 0)
    ll.addWidget(QLabel('报文列表 (勾选=发送):'))
    mw.dbc_msg_list = QListWidget()
    mw.dbc_msg_list.setSelectionMode(QAbstractItemView.SingleSelection)
    ll.addWidget(mw.dbc_msg_list)
    split.addWidget(left)

    right = QWidget()
    rl = QVBoxLayout(right)
    rl.setContentsMargins(0, 0, 0, 0)
    rl.addWidget(QLabel('信号值 (点击报文行选中):'))
    mw.dbc_sig_table = QTableWidget(0, 5)
    mw.dbc_sig_table.setHorizontalHeaderLabels(['信号名', '单位', '最小值', '最大值', '发送值'])
    mw.dbc_sig_table.horizontalHeader().setSectionResizeMode(0, QHeaderView.Stretch)
    mw.dbc_sig_table.setColumnWidth(1, 60)
    mw.dbc_sig_table.setColumnWidth(2, 70)
    mw.dbc_sig_table.setColumnWidth(3, 70)
    mw.dbc_sig_table.setColumnWidth(4, 90)
    mw.dbc_sig_table.verticalHeader().setVisible(False)
    rl.addWidget(mw.dbc_sig_table)
    split.addWidget(right)

    dl.addLayout(split)
    layout.addWidget(dbc_grp)

    # ── 原始 Hex 发送 ──────────────────────────────────────────────
    raw_grp = QGroupBox('原始 Hex 发送')
    rl2 = QVBoxLayout(raw_grp)

    # ID + frame-type checkboxes on one row
    ir = QHBoxLayout()
    ir.addWidget(QLabel('ID (hex):'))
    mw.raw_id_edit = QLineEdit('123')
    mw.raw_id_edit.setFixedWidth(80)
    ir.addWidget(mw.raw_id_edit)
    ir.addSpacing(8)
    mw.raw_ext_check = QCheckBox('扩展帧')
    ir.addWidget(mw.raw_ext_check)
    mw.raw_fd_check = QCheckBox('CAN-FD')
    ir.addWidget(mw.raw_fd_check)
    mw.raw_brs_check = QCheckBox('BRS')
    ir.addWidget(mw.raw_brs_check)
    ir.addStretch()
    rl2.addLayout(ir)

    # Raw hex data — multi-line, 8 bytes per row
    rl2.addWidget(QLabel('数据 (hex, 每行 8 字节):'))
    mw.raw_data_edit = QPlainTextEdit()
    mw.raw_data_edit.setPlainText('00 00 00 00 00 00 00 00')
    mw.raw_data_edit.setFixedHeight(72)
    rl2.addWidget(mw.raw_data_edit)

    # Structured description — one key=value per line, bidirectionally synced
    rl2.addWidget(QLabel('报文描述 (Type: S/E/F/B):'))
    mw.raw_struct_edit = QPlainTextEdit()
    mw.raw_struct_edit.setFixedHeight(96)
    rl2.addWidget(mw.raw_struct_edit)

    sb = QHBoxLayout()
    mw.raw_send_btn = QPushButton('单次发送')
    mw.raw_send_btn.setStyleSheet('QPushButton { background: #26a; color: white; font-weight: bold; }')
    mw.raw_send_btn.setFixedWidth(80)
    sb.addWidget(mw.raw_send_btn)
    sb.addWidget(QLabel('周期(ms):'))
    mw.raw_period_spin = QSpinBox()
    mw.raw_period_spin.setRange(1, 60000)
    mw.raw_period_spin.setValue(100)
    mw.raw_period_spin.setFixedWidth(65)
    sb.addWidget(mw.raw_period_spin)
    mw.raw_period_start_btn = QPushButton('启动')
    mw.raw_period_start_btn.setFixedWidth(50)
    sb.addWidget(mw.raw_period_start_btn)
    mw.raw_period_stop_btn = QPushButton('停止')
    mw.raw_period_stop_btn.setFixedWidth(50)
    mw.raw_period_stop_btn.setEnabled(False)
    sb.addWidget(mw.raw_period_stop_btn)
    sb.addStretch()
    rl2.addLayout(sb)
    rl2.addStretch()
    layout.addWidget(raw_grp)
    mw.main_tab.addTab(tab, '报文发送')


def _build_tab_capture(mw):
    tab = QWidget()
    layout = QVBoxLayout(tab)
    layout.setContentsMargins(4, 4, 4, 4)
    layout.setSpacing(6)
    cap_grp = QGroupBox('录制')
    cap_grp.setMaximumHeight(90)
    cl = QHBoxLayout(cap_grp)
    cl.addWidget(QLabel('格式:'))
    mw.capture_fmt_combo = QComboBox()
    mw.capture_fmt_combo.addItems(['ASC (.asc)', 'BLF (.blf)', 'CSV (.csv)'])
    mw.capture_fmt_combo.setFixedWidth(120)
    cl.addWidget(mw.capture_fmt_combo)
    cl.addWidget(QLabel('文件:'))
    mw.capture_file_label = QLabel('(自动命名)')
    mw.capture_file_label.setMinimumWidth(200)
    cl.addWidget(mw.capture_file_label)
    mw.capture_start_btn = QPushButton('开始录制')
    mw.capture_start_btn.setStyleSheet('QPushButton { background: #c33; color: white; font-weight: bold; }')
    mw.capture_start_btn.setFixedWidth(100)
    cl.addWidget(mw.capture_start_btn)
    mw.capture_stop_btn = QPushButton('停止')
    mw.capture_stop_btn.setFixedWidth(80)
    mw.capture_stop_btn.setEnabled(False)
    cl.addWidget(mw.capture_stop_btn)
    cl.addStretch()
    layout.addWidget(cap_grp)
    rep_grp = QGroupBox('回放')
    rgl = QVBoxLayout(rep_grp)
    rc = QHBoxLayout()
    mw.replay_open_btn = QPushButton('打开文件')
    mw.replay_open_btn.setFixedWidth(90)
    rc.addWidget(mw.replay_open_btn)
    mw.replay_file_label = QLabel('未选择文件')
    mw.replay_file_label.setMinimumWidth(200)
    rc.addWidget(mw.replay_file_label)
    rc.addStretch()
    rc.addWidget(QLabel('速度:'))
    mw.replay_speed_combo = QComboBox()
    mw.replay_speed_combo.addItems(['0.25x', '0.5x', '1x', '2x', '4x', '8x'])
    mw.replay_speed_combo.setCurrentText('1x')
    mw.replay_speed_combo.setFixedWidth(70)
    rc.addWidget(mw.replay_speed_combo)
    rgl.addLayout(rc)
    rb = QHBoxLayout()
    mw.replay_play_btn = QPushButton('播放')
    mw.replay_play_btn.setFixedWidth(70)
    rb.addWidget(mw.replay_play_btn)
    mw.replay_pause_btn = QPushButton('暂停')
    mw.replay_pause_btn.setFixedWidth(70)
    mw.replay_pause_btn.setEnabled(False)
    rb.addWidget(mw.replay_pause_btn)
    mw.replay_stop_btn = QPushButton('停止')
    mw.replay_stop_btn.setFixedWidth(70)
    mw.replay_stop_btn.setEnabled(False)
    rb.addWidget(mw.replay_stop_btn)
    mw.replay_progress_label = QLabel('0%')
    rb.addWidget(mw.replay_progress_label)
    rb.addStretch()
    rgl.addLayout(rb)
    mw.replay_plot = pg.PlotWidget()
    mw.replay_plot.setLabel('bottom', '时间', units='s')
    mw.replay_plot.showGrid(x=True, y=True, alpha=0.3)
    mw.replay_plot.addLegend()
    rgl.addWidget(mw.replay_plot)
    layout.addWidget(rep_grp)
    mw.main_tab.addTab(tab, '捕获 & 回放')


def _build_tab_parse(mw):
    tab = QWidget()
    layout = QVBoxLayout(tab)
    layout.setContentsMargins(4, 4, 4, 4)
    layout.setSpacing(4)

    # ── DBC 管理 (多路) ──────────────────────────────────────────────
    dbc_grp = QGroupBox('DBC 文件管理 (支持多路，每路可单独加载)')
    dbc_grp.setMaximumHeight(145)
    dl = QVBoxLayout(dbc_grp)
    dc = QHBoxLayout()
    mw.parse_add_dbc_btn = QPushButton('添加 DBC')
    mw.parse_add_dbc_btn.setFixedWidth(80)
    dc.addWidget(mw.parse_add_dbc_btn)
    mw.parse_remove_dbc_btn = QPushButton('移除选中')
    mw.parse_remove_dbc_btn.setFixedWidth(80)
    dc.addWidget(mw.parse_remove_dbc_btn)
    mw.parse_clear_dbc_btn = QPushButton('清空')
    mw.parse_clear_dbc_btn.setFixedWidth(55)
    dc.addWidget(mw.parse_clear_dbc_btn)
    dc.addStretch()
    dl.addLayout(dc)
    mw.parse_dbc_table = QTableWidget(0, 4)
    mw.parse_dbc_table.setHorizontalHeaderLabels(['标识', '文件名', '报文数', '信号数'])
    mw.parse_dbc_table.horizontalHeader().setSectionResizeMode(1, QHeaderView.Stretch)
    mw.parse_dbc_table.setColumnWidth(0, 55)
    mw.parse_dbc_table.setColumnWidth(2, 55)
    mw.parse_dbc_table.setColumnWidth(3, 55)
    mw.parse_dbc_table.verticalHeader().setVisible(False)
    mw.parse_dbc_table.setEditTriggers(QAbstractItemView.NoEditTriggers)
    mw.parse_dbc_table.setSelectionBehavior(QAbstractItemView.SelectRows)
    dl.addWidget(mw.parse_dbc_table)
    layout.addWidget(dbc_grp)

    # ── 解析输入 ─────────────────────────────────────────────────────
    inp_grp = QGroupBox('解析输入')
    inp_grp.setMaximumHeight(120)
    il = QVBoxLayout(inp_grp)

    r1 = QHBoxLayout()
    r1.addWidget(QLabel('单帧 ID:'))
    mw.parse_id_edit = QLineEdit()
    mw.parse_id_edit.setFixedWidth(75)
    mw.parse_id_edit.setPlaceholderText('18F')
    r1.addWidget(mw.parse_id_edit)
    r1.addWidget(QLabel('数据:'))
    mw.parse_data_edit = QLineEdit()
    mw.parse_data_edit.setPlaceholderText('A5 B3 00 00 FF 00 00 00')
    r1.addWidget(mw.parse_data_edit)
    mw.parse_btn = QPushButton('解析')
    mw.parse_btn.setFixedWidth(55)
    mw.parse_btn.setStyleSheet('QPushButton { background: #26a; color: white; font-weight: bold; }')
    r1.addWidget(mw.parse_btn)
    mw.parse_from_monitor_btn = QPushButton('从监控导入')
    mw.parse_from_monitor_btn.setFixedWidth(90)
    r1.addWidget(mw.parse_from_monitor_btn)
    il.addLayout(r1)

    r2 = QHBoxLayout()
    r2.addWidget(QLabel('粘贴行:'))
    mw.parse_raw_edit = QLineEdit()
    mw.parse_raw_edit.setPlaceholderText('0.001  0x18F  8  A5 B3 00 00 ...')
    r2.addWidget(mw.parse_raw_edit)
    mw.parse_raw_btn = QPushButton('从文本解析')
    mw.parse_raw_btn.setFixedWidth(90)
    r2.addWidget(mw.parse_raw_btn)
    il.addLayout(r2)

    r3 = QHBoxLayout()
    r3.addWidget(QLabel('日志文件:'))
    mw.parse_log_label = QLabel('(未选择)')
    mw.parse_log_label.setMinimumWidth(160)
    r3.addWidget(mw.parse_log_label)
    mw.parse_open_log_btn = QPushButton('打开文件')
    mw.parse_open_log_btn.setFixedWidth(75)
    r3.addWidget(mw.parse_open_log_btn)
    mw.parse_file_btn = QPushButton('解析文件')
    mw.parse_file_btn.setFixedWidth(75)
    mw.parse_file_btn.setStyleSheet('QPushButton { background: #26a; color: white; font-weight: bold; }')
    r3.addWidget(mw.parse_file_btn)
    r3.addWidget(QLabel('最多:'))
    mw.parse_limit_spin = QSpinBox()
    mw.parse_limit_spin.setRange(100, 100000)
    mw.parse_limit_spin.setValue(5000)
    mw.parse_limit_spin.setSingleStep(1000)
    mw.parse_limit_spin.setFixedWidth(75)
    r3.addWidget(mw.parse_limit_spin)
    r3.addWidget(QLabel('帧'))
    r3.addStretch()
    il.addLayout(r3)

    layout.addWidget(inp_grp)

    # ── 解析结果 ─────────────────────────────────────────────────────
    res_grp = QGroupBox('解析结果')
    rl = QVBoxLayout(res_grp)
    rl.setSpacing(4)

    mw.parse_result_label = QLabel('(请加载 DBC 后进行解析)')
    mw.parse_result_label.setStyleSheet('color: #888; padding: 2px;')
    rl.addWidget(mw.parse_result_label)

    # 帧列表 (上): 点击行 → 下方展示信号详情
    mw.parse_frame_table = QTableWidget(0, 6)
    mw.parse_frame_table.setHorizontalHeaderLabels(
        ['时间(s)', '通道', 'ID', 'DLC', '数据(Hex)', '报文名 [DBC]'])
    mw.parse_frame_table.horizontalHeader().setSectionResizeMode(4, QHeaderView.Stretch)
    mw.parse_frame_table.setColumnWidth(0, 80)
    mw.parse_frame_table.setColumnWidth(1, 50)
    mw.parse_frame_table.setColumnWidth(2, 70)
    mw.parse_frame_table.setColumnWidth(3, 40)
    mw.parse_frame_table.setColumnWidth(5, 150)
    mw.parse_frame_table.verticalHeader().setVisible(False)
    mw.parse_frame_table.setEditTriggers(QAbstractItemView.NoEditTriggers)
    mw.parse_frame_table.setSelectionBehavior(QAbstractItemView.SelectRows)
    mw.parse_frame_table.setAlternatingRowColors(True)
    rl.addWidget(mw.parse_frame_table, 2)

    # 信号详情 (下)
    rl.addWidget(QLabel('信号详情 (点击上方帧行查看):'))
    mw.parse_signal_table = QTableWidget(0, 6)
    mw.parse_signal_table.setHorizontalHeaderLabels(
        ['信号名', '原始值(hex)', '物理值', '单位', '最小值', '最大值'])
    mw.parse_signal_table.horizontalHeader().setSectionResizeMode(0, QHeaderView.Stretch)
    mw.parse_signal_table.setColumnWidth(1, 110)
    mw.parse_signal_table.setColumnWidth(2, 90)
    mw.parse_signal_table.setColumnWidth(3, 60)
    mw.parse_signal_table.setColumnWidth(4, 70)
    mw.parse_signal_table.setColumnWidth(5, 70)
    mw.parse_signal_table.verticalHeader().setVisible(False)
    mw.parse_signal_table.setEditTriggers(QAbstractItemView.NoEditTriggers)
    mw.parse_signal_table.setAlternatingRowColors(True)
    rl.addWidget(mw.parse_signal_table, 3)

    layout.addWidget(res_grp)
    mw.main_tab.addTab(tab, '报文解析')
